// Code generated by cmd/translations/generate_constant.go DO NOT EDIT.
// Hash: 29783db1c61f03bbf13ce5be702e0ee2ebffb65ee0fabd34bc52daf2b2b68f91

package translations

const (
	FormPlayingFormat = "form.playing.format"

	DuelRequestSent = "duel.request.sent"

	ErrorCooldownCommand = "error.cooldown.command"

	PlayerJoinMessage = "player.join.message"

	UserLoadError = "user.load.error"

	ErrorCommandWhisperMissingTarget = "error.command.whisper.missing.target"

	FormFfaSelectorClassic = "form.ffa.selector.classic"

	GameWaitingStartingMessage = "game.waiting.starting.message"

	DuelRequestReceived = "duel.request.received"

	PlayerQuitMessage = "player.quit.message"

	FfaScoreboardYourStreak = "ffa.scoreboard.your.streak"

	ErrorLobbyInCombat = "error.lobby.in.combat"

	GameWaitingScoreboardWaitingForPlayers = "game.waiting.scoreboard.waiting.for.players"

	FormDuelsSelectorNodebuff = "form.duels.selector.nodebuff"

	Broadcast1Message = "broadcast.1.message"

	ErrorSkinChangeNotAllowed = "error.skin.change.not.allowed"

	LobbyScoreboardPlayersOnlineCount = "lobby.scoreboard.players.online.count"

	DeathMessageFormat = "death.message.format"

	ErrorCommandReplyNoTarget = "error.command.reply.no.target"

	FormDuelsSelectorTitle = "form.duels.selector.title"

	GameWaitingJoinMessage = "game.waiting.join.message"

	GameItemQuitName = "game.item.quit.name"

	KilledVoidKnockedMessageFormat = "killed.void.knocked.message.format"

	Broadcast2Message = "broadcast.2.message"

	FormFfaSelectorSumo = "form.ffa.selector.sumo"

	ErrorCommandInvalidTarget = "error.command.invalid.target"

	KilledMessageFormat = "killed.message.format"

	FfaScoreboardYourKills = "ffa.scoreboard.your.kills"

	ErrorCommandWhisperMissingMessage = "error.command.whisper.missing.message"

	WhisperReceived = "whisper.received"

	GameYouDiedTitle = "game.you.died.title"

	ErrorCommandPardonTargetNotFound = "error.command.pardon.target.not.found"

	FfaScoreboardYourDeaths = "ffa.scoreboard.your.deaths"

	ChatMessage = "chat.message"

	GamemodeCommandSuccess = "gamemode.command.success"

	ErrorCommandPardonTargetNotBanned = "error.command.pardon.target.not.banned"

	DuelRequestAborted = "duel.request.aborted"

	DuelRequestMustInLobby = "duel.request.must.in.lobby"

	LobbyItemProfileName = "lobby.item.profile.name"

	FfaScoreboardPlayers = "ffa.scoreboard.players"

	CommandBanSuccess = "command.ban.success"

	LobbyItemPlayDuelsName = "lobby.item.play.duels.name"

	KilledVoidMessageFormat = "killed.void.message.format"

	GameItemPlayAgainName = "game.item.play.again.name"

	CommandAnErrorOccurred = "command.an.error.occurred"

	ErrorCommandReplyTargetOffline = "error.command.reply.target.offline"

	GameWaitingScoreboardStartingIn = "game.waiting.scoreboard.starting.in"

	FormDuelsSelectorClassic = "form.duels.selector.classic"

	ErrorUnknown = "error.unknown"

	ErrorCommandBanTargetAlreadyBanned = "error.command.ban.target.already.banned"

	LobbyItemPlayFfaName = "lobby.item.play.ffa.name"

	LobbyScoreboardPlayersPlayingCount = "lobby.scoreboard.players.playing.count"

	ScoreboardYourPing = "scoreboard.your.ping"

	FormFfaSelectorTitle = "form.ffa.selector.title"

	GameWaitingLeftMessage = "game.waiting.left.message"

	GameEndingScoreboardStoppingIn = "game.ending.scoreboard.stopping.in"

	ErrorPlaceBlock = "error.place.block"

	WelcomeMessage = "welcome.message"

	BannedKickMessage = "banned.kick.message"

	DuelRequestAccepted = "duel.request.accepted"

	ErrorCommandBanTargetNotFound = "error.command.ban.target.not.found"

	ErrorCooldownPearl = "error.cooldown.pearl"

	ErrorCooldownChat = "error.cooldown.chat"

	ScoreboardTheirPing = "scoreboard.their.ping"

	FfaScoreboardCombatTimer = "ffa.scoreboard.combat.timer"

	WhisperSent = "whisper.sent"

	GameStartedMessage = "game.started.message"

	TimeShortDhm = "time.short.dhm"

	PvpInfoTip = "pvp.info.tip"

	ScoreboardTitle = "scoreboard.title"

	FormFfaSelectorBuild = "form.ffa.selector.build"

	FormFfaSelectorNodebuff = "form.ffa.selector.nodebuff"

	ScoreboardFooter = "scoreboard.footer"

	GameWaitingScoreboardPlayers = "game.waiting.scoreboard.players"

	GameScoreboardTimeLeft = "game.scoreboard.time.left"

	CommandTeleportSuccess = "command.teleport.success"

	KilledShotMessageFormat = "killed.shot.message.format"

	DeathVoidMessageFormat = "death.void.message.format"

	GameEndedMessage = "game.ended.message"

	CommandPardonSuccess = "command.pardon.success"

)
