// Code generated by cmd/translations/generate_constant.go DO NOT EDIT.
// Hash: 99aa61ec22d9ee32052be33bfc54ba59a9424d85bcde9f8d88f2f1664e439aa2

package translations

const (
	BannedKickMessage = "banned.kick.message"

	Broadcast1Message = "broadcast.1.message"

	Broadcast2Message = "broadcast.2.message"

	ChatMessage = "chat.message"

	CommandAnErrorOccurred = "command.an.error.occurred"

	CommandBanSuccess = "command.ban.success"

	CommandPardonSuccess = "command.pardon.success"

	CommandTeleportSuccess = "command.teleport.success"

	DeathMessageFormat = "death.message.format"

	DeathVoidMessageFormat = "death.void.message.format"

	DuelRequestAborted = "duel.request.aborted"

	DuelRequestAccepted = "duel.request.accepted"

	DuelRequestMustInLobby = "duel.request.must.in.lobby"

	DuelRequestReceived = "duel.request.received"

	DuelRequestSent = "duel.request.sent"

	ErrorCommandBanTargetAlreadyBanned = "error.command.ban.target.already.banned"

	ErrorCommandBanTargetNotFound = "error.command.ban.target.not.found"

	ErrorCommandInvalidTarget = "error.command.invalid.target"

	ErrorCommandPardonTargetNotBanned = "error.command.pardon.target.not.banned"

	ErrorCommandPardonTargetNotFound = "error.command.pardon.target.not.found"

	ErrorCommandReplyNoTarget = "error.command.reply.no.target"

	ErrorCommandReplyTargetOffline = "error.command.reply.target.offline"

	ErrorCommandWhisperMissingMessage = "error.command.whisper.missing.message"

	ErrorCommandWhisperMissingTarget = "error.command.whisper.missing.target"

	ErrorCooldownChat = "error.cooldown.chat"

	ErrorCooldownCommand = "error.cooldown.command"

	ErrorCooldownPearl = "error.cooldown.pearl"

	ErrorLobbyInCombat = "error.lobby.in.combat"

	ErrorPlaceBlock = "error.place.block"

	ErrorSkinChangeNotAllowed = "error.skin.change.not.allowed"

	ErrorUnknown = "error.unknown"

	FfaScoreboardCombatTimer = "ffa.scoreboard.combat.timer"

	FfaScoreboardPlayers = "ffa.scoreboard.players"

	FfaScoreboardYourDeaths = "ffa.scoreboard.your.deaths"

	FfaScoreboardYourKills = "ffa.scoreboard.your.kills"

	FfaScoreboardYourStreak = "ffa.scoreboard.your.streak"

	FormDuelsSelectorClassic = "form.duels.selector.classic"

	FormDuelsSelectorNodebuff = "form.duels.selector.nodebuff"

	FormDuelsSelectorTitle = "form.duels.selector.title"

	FormFfaSelectorBuild = "form.ffa.selector.build"

	FormFfaSelectorClassic = "form.ffa.selector.classic"

	FormFfaSelectorNodebuff = "form.ffa.selector.nodebuff"

	FormFfaSelectorSumo = "form.ffa.selector.sumo"

	FormFfaSelectorTitle = "form.ffa.selector.title"

	FormPlayingFormat = "form.playing.format"

	GameEndedMessage = "game.ended.message"

	GameEndingScoreboardStoppingIn = "game.ending.scoreboard.stopping.in"

	GameItemPlayAgainName = "game.item.play.again.name"

	GameItemQuitName = "game.item.quit.name"

	GameScoreboardTimeLeft = "game.scoreboard.time.left"

	GameStartedMessage = "game.started.message"

	GameWaitingJoinMessage = "game.waiting.join.message"

	GameWaitingLeftMessage = "game.waiting.left.message"

	GameWaitingScoreboardPlayers = "game.waiting.scoreboard.players"

	GameWaitingScoreboardStartingIn = "game.waiting.scoreboard.starting.in"

	GameWaitingScoreboardWaitingForPlayers = "game.waiting.scoreboard.waiting.for.players"

	GameWaitingStartingMessage = "game.waiting.starting.message"

	GameYouDiedTitle = "game.you.died.title"

	GamemodeCommandSuccess = "gamemode.command.success"

	KilledMessageFormat = "killed.message.format"

	KilledShotMessageFormat = "killed.shot.message.format"

	KilledSelfShotMessageFormat = "killed.self.shot.message.format"

	KilledVoidKnockedMessageFormat = "killed.void.knocked.message.format"

	KilledSelfVoidMessageFormat = "killed.self.void.message.format"

	KilledVoidMessageFormat = "killed.void.message.format"

	LobbyItemPlayDuelsName = "lobby.item.play.duels.name"

	LobbyItemPlayFfaName = "lobby.item.play.ffa.name"

	LobbyItemProfileName = "lobby.item.profile.name"

	LobbyScoreboardPlayersOnlineCount = "lobby.scoreboard.players.online.count"

	LobbyScoreboardPlayersPlayingCount = "lobby.scoreboard.players.playing.count"

	PlayerJoinMessage = "player.join.message"

	PlayerQuitMessage = "player.quit.message"

	PvpInfoTip = "pvp.info.tip"

	ScoreboardFooter = "scoreboard.footer"

	ScoreboardTheirPing = "scoreboard.their.ping"

	ScoreboardTitle = "scoreboard.title"

	ScoreboardYourPing = "scoreboard.your.ping"

	TimeShortDhm = "time.short.dhm"

	UserLoadError = "user.load.error"

	WelcomeMessage = "welcome.message"

	WhisperReceived = "whisper.received"

	WhisperSent = "whisper.sent"

)
